### ISSUE TITLE
Make this app releasable

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-demo-app#90]
We should be going for a releasable application. In this issue I'd like to list and complete all the necessary things that have to be done before the first release is possible. The final product of this issue should be a versioned release of the demo.

**TODO**

- [x] Publish wt-js-libs and move it from a hotlinked js library to an npm dependency - https://github.com/windingtree/wt-js-libs/issues/105
- [x] Resolve any absolutely necessary issues if there are any.
- [x] https://github.com/windingtree/wt-demo-app/issues/19
- [x] #93 
- [x] Enforce node version with .nvm file - https://github.com/creationix/nvm
- [x] Enforce node version with engine field in package.json - https://docs.npmjs.com/files/package.json#engines
- [x] Contribution guidelines - https://github.com/blog/1184-contributing-guidelines #91 
- [x] Up to date documentation in README
- [x] Add eslint

@kvbik I'm not sure if it is the right idea to publish the demo app via npm. What's our goal here? To enable anyone to run this locally and see what is going on? Or to enable anybody to develop on top of what we have?

If we want a channel to distribute a packaged app, I'd go for GiHub releases instead of npm.
For contributing, I think it's pretty standard to stay with `git clone && npm install` or `fork`.

**Comment by czervenka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release Alpha version](https://trello.com/c/Wnt7Wg64/8-release-alpha-version)
